In [9]:
import duckdb

print(duckdb.sql("""
    SELECT DISTINCT
        recipient_uei,
        recipient_name,
        recipient_address_line_1,
        recipient_city_name,
        recipient_state_code,
        LEFT(recipient_zip_4_code, 5) AS zip,
        federal_action_obligation,
        lat,
        lon
    FROM 'master_geocoded.parquet'
    WHERE match = 'Manual'
    LIMIT 20
"""))

#WHERE recipient_uei = 'JJL8JCR5RT31'

┌───────────────┬──────────────────────────────────────────────────────────────────┬───────────────────────────┬─────────────────────┬──────────────────────┬─────────┬───────────────────────────┬─────────────────┬───────────────────┐
│ recipient_uei │                          recipient_name                          │ recipient_address_line_1  │ recipient_city_name │ recipient_state_code │   zip   │ federal_action_obligation │       lat       │        lon        │
│    varchar    │                             varchar                              │          varchar          │       varchar       │       varchar        │ varchar │          varchar          │     double      │      double       │
├───────────────┼──────────────────────────────────────────────────────────────────┼───────────────────────────┼─────────────────────┼──────────────────────┼─────────┼───────────────────────────┼─────────────────┼───────────────────┤
│ L4ZMKLM4MPL3  │ MOOG INC                                                         │ SENECA ST AT JAMISON RD   │ EAST AURORA         │ NY                   │ 14052   │ 158421.00                 │ 42.805112842046 │  -78.645835008713 │
│ FXD9D6JJ3G15  │ QUICKSERIES PUBLISHING INC                                       │ 3325 GRIFFIN RD STE 222   │ FORT LAUDERDALE     │ FL                   │ 33312   │ 6845.00                   │ 26.187851043472 │  -80.191271803316 │
│ FXD9D6JJ3G15  │ QUICKSERIES PUBLISHING INC                                       │ 3325 GRIFFIN RD STE 222   │ FORT LAUDERDALE     │ FL                   │ 33312   │ 9100.00                   │ 26.187851043472 │  -80.191271803316 │
│ E466BXU4KJH8  │ THE BOEING COMPANY                                               │ ROUTE 291 & STEWART AVE   │ RIDLEY PARK         │ PA                   │ 19078   │ 4494.00                   │  39.86991346167 │  -75.322020492513 │
│ FNZKNYDRXTK1  │ AVID TECHNOLOGY, INC.                                            │ 1101 PENN AVE NW STE 600  │ WASHINGTON          │ DC                   │ 20004   │ 152100.00                 │ 38.894807407353 │  -77.027100373587 │
│ X1C4LJLLZNV4  │ TORQHOIST, INC.                                                  │ 4502 PROSPECT RD          │ CLEVELAND           │ OH                   │ 44103   │ 27456.00                  │ 41.424309547893 │  -81.495365065645 │
│ WXWMNR8JNZA3  │ OFFSHORE SERVICE VESSELS, L.L.C.                                 │ 16201 EAST MAIN STREET    │ GALLIANO            │ LA                   │ 70354   │ 0.00                      │   29.4406685238 │  -90.299531278918 │
│ S691K3TH3QG3  │ MECHATRONICS, INC.                                               │ 8152 304TH AVE S E        │ PRESTON             │ WA                   │ 98050   │ 10465.00                  │ 47.527300561662 │ -121.935643495547 │
│ KUBXH5R4DUG5  │ EVMS ACADEMIC PHYSICIANS AND SURGEONS HEALTH SERVICES FOUNDATION │ 4111 MONARCH WAY STE 500  │ NORFOLK             │ VA                   │ 23508   │ 0.00                      │ 36.860386700281 │  -76.302118721775 │
│ M2AMDGJEEL43  │ APPTIS, INC.                                                     │ 4800 WESTFIELDS BLVD      │ CHANTILLY           │ VA                   │ 20151   │ 16426.00                  │ 38.875214068923 │  -77.436866662999 │
│ K2DBK4JPJN73  │ VECTRONIX INC.                                                   │ 801 SYCOLIN RD SESTE 206  │ LEESBURG            │ VA                   │ 20175   │ 0.00                      │ 39.082373474656 │   -77.55259681775 │
│ DQ7YZMCK5D23  │ ICF MACRO INC                                                    │ 11785 BLTSVLLE DR STE 300 │ BELTSVILLE          │ MD                   │ 20705   │ 139412.00                 │ 39.052511964594 │  -76.935603591734 │
│ MTH4KUW6VMJ3  │ CROWN GYM MATS INC                                               │ 27 W 929 INDUSTRIAL AV    │ BARRINGTON          │ IL                   │ 60010   │ 0.00                      │ 42.184868103149 │  -88.177764742382 │
│ L4ZMKLM4MPL3  │ MOOG INC                                                         │ SENECA ST AT JAMISON RD   │ EAST AURORA         │ NY                   │ 14052   │ 5369.00                   │ 42.805112842046 │  -78.645835008713 │
│ S33FXH3CVKJ5  │ RICOH AMERICAS CORPORATION                                       │ FIVE DEDRICK PLACE        │ WEST CALDWELL       │ NJ                   │ 07006   │ 8585.22                   │ 40.855490403293 │  -74.294280587111 │
│ GKUMJS8XRVP5  │ THE CHEROKEE 8A GROUP, INC.                                      │ 115 N MN ST               │ WHARTON             │ NJ                   │ 07885   │ -4196.00                  │ 40.902503591864 │  -74.579791286016 │
│ S1UJKLXH5BB3  │ CESC MALL LLC                                                    │ CESC MALL LLC             │ ARLINGTON           │ VA                   │ 22202   │ 0.00                      │ 38.852934709647 │  -77.049553627934 │
│ KWNWSMM5BG17  │ SIGNAL SOLUTIONS, LLC                                            │ 3040 WILLIAMS DRIVE       │ FAIRFAX             │ VA                   │ 22031   │ -369213.00                │ 38.873814177947 │  -77.314375735739 │
│ LP6HLAULH3C5  │ TYEE AIRCRAFT INC                                                │ 6500 MERRILL CREEK PKWY   │ EVERETT             │ WA                   │ 98203   │ 81794.00                  │ 47.907591518654 │ -122.273210661435 │
│ Y9N9RGT6VKH8  │ NOVA GROUP, INC.                                                 │ 7411 NAPA-VALLEJO HWY     │ NAPA                │ CA                   │ 94558   │ 197068.00                 │ 38.237824231121 │ -122.265862869045 │
├───────────────┴──────────────────────────────────────────────────────────────────┴───────────────────────────┴─────────────────────┴──────────────────────┴─────────┴───────────────────────────┴─────────────────┴───────────────────┤
│ 20 rows                                                                                                                                                                                                                     9 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [5]:
import duckdb

con = duckdb.connect()

df = con.execute("""
    SELECT * FROM 'master_cleaned.parquet' LIMIT 0
""").fetchdf()

print(df.columns.tolist())

['contract_transaction_unique_key', 'contract_award_unique_key', 'award_id_piid', 'modification_number', 'federal_action_obligation', 'total_dollars_obligated', 'total_outlayed_amount_for_overall_award', 'current_total_value_of_award', 'potential_total_value_of_award', 'action_date', 'action_date_fiscal_year', 'period_of_performance_start_date', 'period_of_performance_current_end_date', 'awarding_agency_code', 'awarding_agency_name', 'awarding_sub_agency_code', 'awarding_sub_agency_name', 'awarding_office_code', 'awarding_office_name', 'funding_agency_code', 'funding_agency_name', 'funding_sub_agency_code', 'funding_sub_agency_name', 'recipient_uei', 'recipient_duns', 'recipient_name', 'recipient_name_raw', 'recipient_parent_uei', 'recipient_parent_duns', 'recipient_parent_name', 'recipient_country_code', 'recipient_country_name', 'recipient_address_line_1', 'recipient_city_name', 'recipient_county_name', 'recipient_state_code', 'recipient_state_name', 'recipient_zip_4_code', 'prime_award_transaction_recipient_cd_original', 'prime_award_transaction_recipient_cd_current', 'award_or_idv_flag', 'award_type_code', 'award_type', 'product_or_service_code', 'product_or_service_code_description', 'naics_code', 'naics_description', 'transaction_description', 'prime_award_base_transaction_description', 'action_type_code', 'action_type', 'clean_uei', 'clean_name', 'clean_address', 'clean_city', 'clean_state', 'clean_zip']

In [6]:
import duckdb

con = duckdb.connect()

con.execute("""
COPY (
    SELECT
        m.*,
        g.lat,
        g.lon,
        g.match,
        u.address_id
    FROM 'master_cleaned.parquet' m

    LEFT JOIN read_csv_auto('uei_name_lookup.csv') u
        ON m.clean_uei = u.uei
        AND m.clean_name = u.name
        AND m.clean_address = u.address
        AND m.clean_city = u.city
        AND m.clean_state = u.state
        AND m.clean_zip = u.zip

    LEFT JOIN read_csv_auto('geocoded_addresses_from_script.csv') g
        ON u.address_id = g.id

)
TO 'master_geocoded.parquet'
(FORMAT PARQUET);
""")

con.close()

In [2]:
import duckdb

con = duckdb.connect()

con.execute("""
SELECT
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE prime_award_transaction_recipient_cd_current IS NULL) AS missing_cd,
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE prime_award_transaction_recipient_cd_current IS NULL) / COUNT(*),
        2
    ) AS missing_cd_percent
FROM 'master_geocoded.parquet'
""").fetchdf()

   total_rows  missing_cd  missing_cd_percent
0    55764141       31715                0.06

In [8]:
con.execute("""
SELECT
    COUNT(*) AS unmatched_geocodes,
    
    COUNT(*) FILTER (WHERE prime_award_transaction_recipient_cd_current IS NOT NULL) AS unmatched_with_cd,
    
    ROUND(
        100.0 * COUNT(*) FILTER (WHERE prime_award_transaction_recipient_cd_current IS NOT NULL) / COUNT(*),
        2
    ) AS percent_with_cd
    
FROM 'master_geocoded.parquet'
WHERE (match != 'Match' AND match != 'Manual')
   OR match IS NULL
""").fetchdf()

   unmatched_geocodes  unmatched_with_cd  percent_with_cd
0             4632868            4629508            99.93

In [7]:
con.execute("""
SELECT COUNT(*) AS distinct_addresses
FROM ( 
  SELECT DISTINCT
    clean_uei,
    clean_name,
    clean_address,
    clean_city,
    clean_state,
    clean_zip,
    match,
    lat,
    lon
  FROM 'master_geocoded.parquet'
  WHERE ((match != 'Match' AND match != 'Manual') OR match IS NULL)
    AND prime_award_transaction_recipient_cd_current IS NULL
)
""").fetchdf()

   distinct_addresses
0                 192

In [10]:
con.execute("""
SELECT
    clean_uei,
    clean_name,
    clean_address,
    clean_city,
    clean_state,
    clean_zip,
    COUNT(*) AS transactions,
    SUM(TRY_CAST(federal_action_obligation AS DECIMAL(18,2))) AS total_obligation
FROM 'master_geocoded.parquet'
WHERE ((match != 'Match' AND match != 'Manual') OR match IS NULL)
  AND prime_award_transaction_recipient_cd_current IS NULL
GROUP BY
    clean_uei,
    clean_name,
    clean_address,
    clean_city,
    clean_state,
    clean_zip
ORDER BY total_obligation DESC
""").fetchdf()

,clean_uei,clean_name,clean_address,clean_city,clean_state,clean_zip,transactions,total_obligation
0,QN1BCFY7JDJ5,RTX CORPORATION,400 MAIN ST,EAST HARTFORD,FL,06108,517,7.313157e+08
1,C76NUJZDXL75,WSP USA ENVIRONMENT & INFRASTRUCTURE INC.,ONE PLYMOUTH MEETING,PLYMOUTH MEETI,PA,19462,221,1.491642e+08
2,DJKNQ7AWDQL8,"TRAX INTERNATIONAL, LLC",WHITE SANDS MR,WHITE SANDS MI,NM,88002,80,1.167585e+08
3,EJGKYVW1NLL5,"POLARIS ALPHA, LLC",5450 TECH CENTER DR,COLORADO SPRIN,CO,80919,117,7.590016e+07
4,ENNHFPHSDEX4,PERATON INC.,8955A DRENNAN RD,COLORADO SPRIN,CO,80925,31,5.257173e+07
...,...,...,...,...,...,...,...,...
187,M3J1B3ML1CE5,"CRANE ELECTRONICS, INC.",84 HILL AVE,FORT WALTON BE,FL,32548,6,-4.297360e+05
188,TLJZWFZZQMF6,"M2 TECHNOLOGIES, INC.",498 ELLIOTT RD CENTERVI,WEST HYANNISPO,MA,02672,8,-5.273063e+05
189,V6Y5MMVCJLL5,"KELLOGG BROWN & ROOT SERVICES, INC.",2316 BRANDENBURG STATION R,FORT KNOX,MI,40121,1,-7.851400e+05
190,JE47BHSEWSP4,ADVANCED TECHNICAL PRODUCTS INC,ONE GARVIES PT RD,GLEN COVE,GA,11542,22,-1.066736e+06
191,CN7PNYLZLNV3,"L3HARRIS TECHNOLOGIES, INC.",1500 NEW HORIZONS BOULEVAR,NORTH AMITYVIL,NY,11701,56,-2.549619e+06

In [23]:
con.execute("""
SELECT DISTINCT
  clean_uei,
  clean_name,
  clean_address,
  clean_city,
  clean_state,
  clean_zip
FROM 'master_geocoded.parquet'
WHERE (clean_zip IS NULL OR TRIM(clean_zip) = '')
  AND prime_award_transaction_recipient_cd_current IS NOT NULL
  AND lat IS NULL
  AND lon IS NULL
""").fetchdf()

,clean_uei,clean_name,clean_address,clean_city,clean_state,clean_zip
0,CNMRBP7GV796,TELEGUAM HOLDINGS LLC,624 N MARINE CORPS DR,TAMUNING,GU,None
1,GPXJYERQRVK4,NAVIG8 CHEMICALS POOL INC.,TRUST COMPANY COMPLEX AJELTAK,MAJURO,MH,None
2,GAXHMJHP2YS1,"GUAM CABLEVISION, LLC",600 HARMON LOOP RD,DEDEDO 96929,GU,None
3,S7QSS3NZXE26,DALLAS ENTERPRISES,AMELCO BUILDING RT 15 - PAGAT,MANGILAO,GU,None
4,DN6DLL9MNNX5,KWIKSPACE GUAM INC,CHALAN SAN ANTONIO LOT 2145,"AGANA, 96932",GU,None
5,F8F6D1RJ4ST3,TRINITY EVANGELICAL DIVINITY S,2065 HALF DAY RD,DEERFIELD,IL,None
6,MFELCMEAUVS5,"LESCANO, JOSEPH L",1270 NORTH MARNE DR,TAMUNING,GU,None
7,RQ7EQKRLK5Q9,ST MATTHEWS LIMITED LIABILITY COMPANY,SE 101 2025 ARMY DR,DEDEDO,GU,None
8,DN6DLL9MNNX5,KWIKSPACE GUAM INC,256 MARINE CORPS DR ROUTE 1,PITI,GU,None
9,FGS7N9Q9MMW5,INTERNATIONAL BRIDGE CORPORATION,171 MARINE CORP DR,YIGO 96929,GU,None
10,WWN9XJR37BK5,NORBERT A BROSCH,SCHLOSSTR 7,71570,DE,None
11,GMBCK22AS5T7,TECH DESK,30 GILMORE AVE,SANTA RITA,GU,None
12,W4EFKA5KUB33,YONA-TALOFOFO FARMS,140 KOLEPBLA CRT,YONA,GU,None
13,MAHHATBMHWU7,TINIAN CENTER INC,SAN JOSE VILLAGE,TINIAN 96952,MP,None
14,Y274QXZPQC46,SPORTHOTEL GARMISCH-PARTENKIRCHEN GMBH & CO. K...,MITTENWALDER STRASSE 59,GARMISCH,DE,None
15,U229GJDEH8B5,"PACIFIC AIRPORT SERVICES, INC.",SAIPAN INTERNATIONAL AIRPORT,DANDAN,MP,None
16,WF9MPU5U83V6,OCEAN VIEW PLAZA-WEST WING,DOLONIER NETT,KOLONIA,FM,None
17,C2HLLDKPK7L6,"RENTALS PLUS, LLC",255 EAST MARINE DR,HAGATNA,GU,None
18,K9U3EPADLTH9,SOUND'S UNLIMITED,346F MARTINEZ LN,MONGMONG,GU,None
19,CRFKYEH8X5C6,GUAM MARRIOTT RESORT & SPA,627B PALE SAN VITORES RD,TUMON 96913,GU,None
20,RJN7QMM22259,GTA,624 N MARINE DR,TAMUNING,GU,None
21,DTX5XA4BB271,C B M CAPITAL BUILDING MAINTENANCE INCORPORATED,DENVER ST,SAN JUAN,PR,None
22,GHRFE15TLXS3,COMMONWEALTH UTILITIES CORPORATION,PO BOX 501220,SAIPAN,MP,None
23,SLCKM8J8VJC5,JACALYN MORGAN,118 MENDIOLA LN,AGANA HEIGHTS 969106307,GU,None
24,MNN8BSL5VMK5,SIGNAL PROJECTS LTD,TRUST COMPANY COMPLEX AJELKA,AJELTAKE ISLAND MH96960,MH,None
25,Q5NQQU38UA36,TRANS PACIFIC TRAVEL INC,207 MARTYR ST,AGANA 96932,GU,None
26,LBWLXQ3EX9G5,PACIFIC SURGICAL ARTS,318 DUENAS DR,TAMUNING,GU,None
27,D7A8L4XFGDV4,FRONTIER (GUAM) CORPORATION,1090 ARMY DR,BARRIGADA,GU,None
28,DMBCL7H2ENS5,7-D RENTALS CO,NIMAAR WELOY,COLONIA,FM,None
29,HW3QCJSK6EK3,POHNPEI ISLAND ARCHITECT & CONSTRUCTION,MAPWUSI RD,KOLONIA,FM,None
30,HJGSSMJCYXN4,TANGO INC.,1088 WMARINE CORPS DR,DEDEDO,GU,None
31,JYA5GMZRJJB5,HAFA ADAI SIGNS,283 EAST AGANA,HAGATNA,GU,None
32,UJW7C2AF7EL3,SANFORD TECHNOLOGY GROUP LLC,335 S MARINE DR SANFORD SE,TAMUNING 96913,GU,None
33,J5C7LCA8QKM8,ACNS MARIANAS,1433 PALE SAN VITORES RD,TAMUNING 96913,GU,None
34,LB5AQJ8TKPX1,SENTEGA ETIKETTEN DEUTSCHLAND,MIESBACHER STRASSE 5,83626 VALLEY,DE,None
35,QZ15ZCVBPTN3,PALAU NATIONAL COMMUNICATIONS CORPORATION,1 AIRPORT CIR,KOROR,FM,None
36,YC7FW9GXNM85,SCORPIO HANDYMAX TANKER POOL LTD,AJELTAKE RD,MAJURO 96960,MH,None
37,HZE9TVJ5MEP9,DYNAMIC GENERAL SERVICES,114 NGERBECHED RD,KOROR,PW,None
38,D5K9JP6G27K1,POHNPEI ACE HARDWARE,,POHNPEI,FM,None
39,MLYLBJJ86GK7,GEORGE B. CASTRO,49 ANACOCO LN,PITI 96915,GU,None
40,MGDVFBVRLGG5,MICRONESIAN TELECOMMUNICATIONS CORPORATION,TEKKEN ST,NaN,MP,None
41,MZBJYLPUA7K8,"PACIFIC BIOMEDICAL SERVICES, INC",PATNITOS LN,"SAIPAN, 96950",MP,None
42,LKEDHV4G1C84,B & R CORPORATION,LOUGHAL PL,"SAIPAN, MP 96950",MP,None
43,GPXJYERQRVK4,NAVIG8 CHEMICALS POOL INC.,TRUST COMPANY COMPLEX AJELTAK,MAJURO MH 96960,MH,None

In [6]:
con.execute("""
SELECT
    COUNT(DISTINCT bad.clean_uei || '|' || bad.clean_address) AS unmatched_unique_addresses,
    COUNT(DISTINCT CASE WHEN good.lat IS NOT NULL THEN bad.clean_uei || '|' || bad.clean_address END) AS addresses_with_other_geocode
FROM 'master_geocoded.parquet' bad

LEFT JOIN 'master_geocoded.parquet' good
    ON bad.clean_uei = good.clean_uei
    AND bad.clean_address = good.clean_address
    AND good.lat IS NOT NULL

WHERE (bad.match != 'Match' OR bad.match IS NULL)
""").fetchdf()

   unmatched_unique_addresses  addresses_with_other_geocode
0                       29664                           250

In [11]:
con.execute("""
WITH bad AS (
    SELECT DISTINCT
        clean_uei,
        clean_city
    FROM 'master_geocoded.parquet'
    WHERE ((match != 'Match' AND match != 'Manual') OR match IS NULL)
),

good AS (
    SELECT DISTINCT
        clean_uei,
        clean_city
    FROM 'master_geocoded.parquet'
    WHERE lat IS NOT NULL
)

SELECT
    COUNT(*) AS unmatched_unique_uei_city,
    COUNT(g.clean_uei) AS with_other_geocode
FROM bad b
LEFT JOIN good g
    ON b.clean_uei = g.clean_uei
    AND b.clean_city = g.clean_city
""").fetchdf()

   unmatched_unique_uei_city  with_other_geocode
0                      26478                4593

In [5]:
con.execute("""
COPY (
    SELECT
        bad.* EXCLUDE (lat, lon, match),

        COALESCE(bad.lat, good.lat) AS lat,
        COALESCE(bad.lon, good.lon) AS lon,

        CASE
            WHEN bad.lat IS NULL AND good.lat IS NOT NULL THEN 'Manual'
            ELSE bad.match
        END AS match

    FROM 'master_geocoded.parquet' bad

    LEFT JOIN (
        SELECT DISTINCT
            clean_uei,
            clean_address,
            lat,
            lon
        FROM 'master_geocoded.parquet'
        WHERE lat IS NOT NULL
    ) good
        ON bad.clean_uei = good.clean_uei
        AND bad.clean_address = good.clean_address

)
TO 'master_geocoded.parquet'
(FORMAT PARQUET);
""")

In [6]:
import duckdb

con = duckdb.connect()

con.execute("""
COPY (
    SELECT
        bad.* EXCLUDE (lat, lon, match),

        COALESCE(bad.lat, good.lat) AS lat,
        COALESCE(bad.lon, good.lon) AS lon,

        CASE
            WHEN bad.lat IS NULL AND good.lat IS NOT NULL THEN 'Manual'
            ELSE bad.match
        END AS match

    FROM 'master_geocoded.parquet' bad

    LEFT JOIN (
        SELECT
            clean_uei,
            clean_city,
            ANY_VALUE(lat) AS lat,
            ANY_VALUE(lon) AS lon
        FROM 'master_geocoded.parquet'
        WHERE lat IS NOT NULL
        GROUP BY
            clean_uei,
            clean_city
        HAVING COUNT(DISTINCT lat || ',' || lon) = 1
    ) good
        ON bad.clean_uei = good.clean_uei
        AND bad.clean_city = good.clean_city

)
TO 'master_geocoded.parquet'
(FORMAT PARQUET);
""")